CREATE TABLE My_Category (
    Cat_ID NUMBER PRIMARY KEY,
    Cat_Name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE My_Exp (
    Exp_ID NUMBER PRIMARY KEY,
    Exp_Date DATE NOT NULL,
    Exp_Item VARCHAR2(100) NOT NULL,
    Exp_Amount NUMBER(10, 0) NOT NULL,
    Cat_ID NUMBER,
    FOREIGN KEY (Cat_ID) REFERENCES My_Category (Cat_ID)
);

CREATE SEQUENCE My_Category_Seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE My_Exp_Seq START WITH 1 INCREMENT BY 1;

ALTER TABLE My_Exp
DROP CONSTRAINT SYS_C007463;

-- on delete cascade 부여
ALTER TABLE My_Exp
ADD CONSTRAINT FK_EXP_CAT_CASCADE
FOREIGN KEY (Cat_ID)
REFERENCES My_Category (Cat_ID)
ON DELETE CASCADE;