CREATE SEQUENCE MWM_SELLER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE MWM_SELLER (
    SELLER_NO       NUMBER          CONSTRAINT PK_MWM_SELLER PRIMARY KEY,
    SELLER_NAME     VARCHAR2(15)    CONSTRAINT NN_MWM_S_NAME NOT NULL,
    RESIDENCE       VARCHAR2(30)    CONSTRAINT NN_MWM_RESIDENCE NOT NULL,
    BIRTH_DATE      DATE            CONSTRAINT NN_MWM_B_DATE NOT NULL
);

CREATE SEQUENCE MWM_PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE MWM_PRODUCT (
    PRODUCT_ID      NUMBER          CONSTRAINT PK_MWM_PRODUCT PRIMARY KEY,
    SELLER_NO       NUMBER          CONSTRAINT FK_MWM_PRODUCT_SELLER REFERENCES MWM_SELLER(SELLER_NO) ON DELETE CASCADE,
    PRODUCT_NAME    VARCHAR2(40)    CONSTRAINT NN_MWM_P_NAME NOT NULL,
    PRICE           NUMBER          CONSTRAINT NN_MWM_PRICE NOT NULL CONSTRAINT CHK_MWM_PRICE CHECK (PRICE > 0),
    CATEGORY        VARCHAR2(15),
    CONSTRAINT UQ_MWM_SELLER_PROD UNIQUE (SELLER_NO, PRODUCT_NAME)
);
