-- 1. 판매자 '홍길동' 데이터 삽입
INSERT INTO MWM_SELLER (SELLER_NO, SELLER_NAME, RESIDENCE, BIRTH_DATE)
VALUES (MWM_SELLER_SEQ.NEXTVAL, '홍길동', '수원', DATE '1999-01-01');

-- 2. 제품 '모나미153' 데이터 삽입
-- SELLER_NO는 방금 삽입된 홍길동의 번호(CURRVAL)를 사용합니다.
INSERT INTO MWM_PRODUCT (PRODUCT_ID, SELLER_NO, PRODUCT_NAME, PRICE, CATEGORY)
VALUES (MWM_PRODUCT_SEQ.NEXTVAL, MWM_SELLER_SEQ.CURRVAL, '모나미153', 500, '문구류');

SELECT * FROM MWM_SELLER ms;
SELECT * FROM MWM_PRODUCT mp;