SELECT * FROM seoul_air_quality;

-- 테이블명: SEOUL_AIR_QUALITY

ALTER TABLE SEOUL_AIR_QUALITY RENAME COLUMN MSRMT_DT TO saq_date;
ALTER TABLE SEOUL_AIR_QUALITY RENAME COLUMN SAREA_NM TO saq_area;
ALTER TABLE SEOUL_AIR_QUALITY RENAME COLUMN MSRSTN_NM TO saq_district;
ALTER TABLE SEOUL_AIR_QUALITY RENAME COLUMN PM TO saq_pm10;
ALTER TABLE SEOUL_AIR_QUALITY RENAME COLUMN FPM TO saq_pm25;
ALTER TABLE SEOUL_AIR_QUALITY RENAME COLUMN CAI_IDX TO saq_score;

-- 참고: 기본키도 변경된 컬럼명을 사용하도록 재정의해야 할 수도 있습니다.
ALTER TABLE SEOUL_AIR_QUALITY DROP PRIMARY KEY;
ALTER TABLE SEOUL_AIR_QUALITY ADD CONSTRAINT PK_SEOUL_AIR_QUALITY PRIMARY KEY (saq_date, saq_district);